// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl7lcJQrifQFr27oZwKGx99Urgrz54nhU',
    appId: '1:530643300187:android:4fda4f32942bee6f7ab47e',
    messagingSenderId: '530643300187',
    projectId: 'e-shop-78ab5',
    authDomain: 'e-shop-78ab5.firebaseapp.com',
    storageBucket: 'e-shop-78ab5.appspot.com',
    measurementId: 'G-D3S30R5PSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl7lcJQrifQFr27oZwKGx99Urgrz54nhU',
    appId: '1:530643300187:android:4fda4f32942bee6f7ab47e',
    messagingSenderId: '530643300187',
    projectId: 'e-shop-78ab5',
    storageBucket: 'e-shop-78ab5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl7lcJQrifQFr27oZwKGx99Urgrz54nhU',
    appId: '1:530643300187:android:4fda4f32942bee6f7ab47e',
    messagingSenderId: '530643300187',
    projectId: 'e-shop-78ab5',
    storageBucket: 'e-shop-78ab5.appspot.com',
    iosClientId:
        '106395754985-49gshn2jbmcvg5g979rra2oqnqp6h3nt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl7lcJQrifQFr27oZwKGx99Urgrz54nhU',
    appId: '1:530643300187:android:4fda4f32942bee6f7ab47e',
    messagingSenderId: '530643300187',
    projectId: 'e-shop-78ab5',
    storageBucket: 'e-shop-78ab5.appspot.com',
    iosClientId:
        '106395754985-49gshn2jbmcvg5g979rra2oqnqp6h3nt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eshop',
  );
}
